apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: certificate-transparency-go
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/certificate-transparency-go/certificate-transparency-go@sha256:44dbd40c0217486ba1996f733f9dda65dff701f4a97f54629cdfdc409b53e9a8
        name: my-go
        resources: {}
status: {}
