apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: certificate-transparency-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate-transparency-go
    app.kubernetes.io/part-of: certificate-transparency-go
  name: certificate-transparency-cwrh
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: certificate-transparency-go
    weight: null
status: {}
