apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: certificate-transparency-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate-transparency-go
    app.kubernetes.io/part-of: certificate-transparency-go
  name: certificate-transparency-go
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: certificate-transparency-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: certificate-transparency-go
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/certificate-transparency-go/certificate-transparency-go@sha256:80bf91034e39a56d4456857b9caf71ae807c1eb29b3e1aff5711c620512ce71d
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
