apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: certificate-transparency-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate-transparency-go
    app.kubernetes.io/part-of: certificate-transparency-go
  name: certificate-transparency-go
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: certificate-transparency-go
status:
  loadBalancer: {}
